version: '2'
services:  
  app:
    container_name: legsite_app
    build: .
    command: /bin/bash -c "npm run dev"
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8080:8080
